apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532

  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  - name: docker-credentials
    secret:
      secretName: docker-creds

  params:
  - name: repo-url
    value: https://github.com/iamdempa/tekton-demos.git

  - name: image-name
    value: "19950818/test:1"

  - name: image-context
    value: BuildDockerImage/sources