apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/iamdempa/tekton-demos.git
    - name: gitRevision
      value: main
    - name: pathToYamlFile
      value: sources/deployment.yaml
    - name: imageUrl
      value: nginx
    - name: imageTag
      value: "1.23"
  # serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      emptyDir: {}
      # persistentVolumeClaim:
      #   claimName: picalc-source-pvc